name: scrap-sitemap

on:
  workflow_dispatch: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

  schedule: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron:  '00 00 * * *'  # every day at 00:00 UTC

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.2.1'

jobs:
  scrap-tv-program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Verify poetry.lock agrees with pyproject.toml
        run: poetry lock --check
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: RunScrappingScript
        env: # TOKEN as an environment variable
          SLACK_TOKEN: ${{ secrets.SlackTokenSecret }}
        run: |
          poetry run python quotaclimat/data_ingestion/scrap_sitemap.py
      - name: Push data to the repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "ci (scrap data): sitemap"
          git push origin main --force
      - name: Failure Logging Step
        if: ${{ failure() }}
        run: |
          poetry run python quotaclimat/logging/log_error.py "${{ steps.response.outputs.result }}"
